### ISSUE TITLE
which version of pytorch is used?

### ISSUE THREAD

**Issue by xhuanlc** [michuanhaohao/AlignedReID#1]
Hello Hao,
Would you tell me what's the version of pytorch you are using please?
Will appreciate if u can add a requirements list of this project.
Cheers,
Chao

**Comment by ShadowLau** [comment]
@xhuanlc pytorch0.4.0 and python2.7 work for me on ubuntu14.04

**Comment by michuanhaohao** [comment]
@xhuanlc I use pytorch0.4.0 and python2.7. Python3 is unavailable.

**Comment by michuanhaohao** [comment]
See README
