### ISSUE TITLE
Something wrong with market1501?

### ISSUE THREAD

**Issue by wuqiangch** [michuanhaohao/AlignedReID#10]
I run the bellow script:
python train_alignedreid_org.py  -d market1501 -a resnet50 --test_distance global_local --reranking
and get the result
==> Test
Extracted features for query set, obtained 3368-by-2048 matrix
Extracted features for gallery set, obtained 15913-by-2048 matrix
==> BatchTime(s)/BatchSize(img): 0.096/32
Only using global branch
Computing local distance...
Matrix part (17, 80) / (17, 80), +0.23s, total 307.60s
Using global and local branches
Computing CMC and mAP
Results ----------
mAP: 28.9%
CMC curve
Rank-1  : 53.9%
Rank-5  : 75.3%
Rank-10 : 82.6%
Rank-20 : 87.5%
------------------
Computing local distance...
Matrix part (17, 17) / (17, 17), +0.20s, total 64.45s
Computing local distance...
Matrix part (80, 80) / (80, 80), +0.25s, total 1443.70s
Using global and local branches for reranking
using GPU to compute original distance
starting re_ranking
Computing CMC and mAP for re_ranking
Results ----------
mAP(RK): 40.3%
CMC curve(RK)
Rank-1  : 56.0%
Rank-5  : 74.0%
Rank-10 : 79.9%
Rank-20 : 85.2%
------------------
==> Best Rank-1 56.0%, achieved at epoch 300
Finished. Total elapsed time (h:m:s): 3:02:26. Training time (h:m:s): 2:19:29.

**Comment by michuanhaohao** [comment]
@wuqiangch I think the results can be reproduced and can not infer the errors from your log information. Do you modify some files? There dose not exist the file named "train_alignedreid_org.py". And what is the version of your pytorch. I remember there are some differences between pytorch 0.4.0 and pytorch 0.4.1.

**Comment by leileiaixiaoqiang** [comment]
> ## I run the bellow script:
> python train_alignedreid_org.py -d market1501 -a resnet50 --test_distance global_local --reranking
> and get the result
> ==> Test
> Extracted features for query set, obtained 3368-by-2048 matrix
> Extracted features for gallery set, obtained 15913-by-2048 matrix
> ==> BatchTime(s)/BatchSize(img): 0.096/32
> Only using global branch
> Computing local distance...
> Matrix part (17, 80) / (17, 80), +0.23s, total 307.60s
> Using global and local branches
> Computing CMC and mAP
> Results ----------
> mAP: 28.9%
> CMC curve
> Rank-1 : 53.9%
> Rank-5 : 75.3%
> Rank-10 : 82.6%
> Rank-20 : 87.5%
> ## Computing local distance...
> Matrix part (17, 17) / (17, 17), +0.20s, total 64.45s
> Computing local distance...
> Matrix part (80, 80) / (80, 80), +0.25s, total 1443.70s
> Using global and local branches for reranking
> using GPU to compute original distance
> starting re_ranking
> Computing CMC and mAP for re_ranking
> Results ----------
> mAP(RK): 40.3%
> CMC curve(RK)
> Rank-1 : 56.0%
> Rank-5 : 74.0%
> Rank-10 : 79.9%
> Rank-20 : 85.2%
> ==> Best Rank-1 56.0%, achieved at epoch 300
> Finished. Total elapsed time (hⓂ️s): 3:02:26. Training time (hⓂ️s): 2:19:29.

hi？i met the same problem same like your's,have you solvd the issue?how do you deal with it?could you please tell me?thx?
