### ISSUE TITLE
Hello? I have some doubts about my results on CUHK03

### ISSUE THREAD

**Issue by romanticegg** [michuanhaohao/AlignedReID#14]
I have done some improvements on your network structure, but the results on CUHK03(detected) have surprised me, it got 84.6%mAP and 77.3% rank 1 accuracy for CUHK03. I don't believe this result so I doubt whether there is anything wrong with my command? My command is as follows: python train_alignedreid.py  -d cuhk03 --use-metric-cuhk03 -a resnet50 --test_distance global_local  --stepsize 300  --lr 0.0002   --save-dir ./log/try/  --train-batch 128 --eval-step 150  --max-epoch 60000  --reranking  --height 384 --width 128

**Comment by michuanhaohao** [comment]
@romanticegg If you want compare the results with some published papers on CUHK03, you should remove ' --use-metric-cuhk03'. You can get more details from the 'Readme.md' file. 

Old test protocol:  ' --use-metric-cuhk03' + '--cuhk03-classic-split'
New test protocol: default (do nothing)

**Comment by romanticegg** [comment]
@michuanhaohao Oh I know the problem. You are nice! Thanks a lot!
