### ISSUE TITLE
Could you provide models with google drive ?

### ISSUE THREAD

**Issue by Qidian213** [michuanhaohao/AlignedReID#16]
Although i am in china , it is inconvenient to use baidu yun on linux with big file .
Even on windows it has very very low speed to down .
Thanks !

**Comment by michuanhaohao** [comment]
@Qidian213  Google Drive: https://drive.google.com/open?id=1-QApSAY51NvRcQgyUxCn8lP1sSWCeMVg

**Comment by Qidian213** [comment]
谢谢
