### ISSUE TITLE
About mutual learning 

### ISSUE THREAD

**Issue by Qidian213** [michuanhaohao/AlignedReID#18]
It seems that the code not include mutual learning when training , but i guess you should did it in paper. Would it be usable after paper be accepted ？Thanks !

**Comment by michuanhaohao** [comment]
@Qidian213 Mutual learning has been removed from AlignedReID++. If you want to reproduce the mutual learning, you can refer to https://github.com/huanghoujing/AlignedReID-Re-Production-Pytorch

**Comment by Qidian213** [comment]
Thanks ! I had did it by myself ,later may push a test result.

**Comment by Qidian213** [comment]
你好，我按着https://github.com/huanghoujing/AlignedReID-Re-Production-Pytorch思路做了deep mutual learning .使用resnet50 ,inceptionv4 两个模型，DukeMTMCreID数据集。发现个现象：单独训练时都能收敛，但是mutual learning时 1，只使用分类做mutual loss 时resnet50能收敛但最后效果不如单独训练时（测试rank-1 83%），inceptionv4 刚开始收敛大概15epochs后开始发散，发散到一定程度后稳定， 最后对resetnet50测试 rank-1 82.1% 。2，只使用global distance做mutual loss 时两个模型都能收敛最后测试resnet50 rank-1 80.0%，inceptionv4 rank-1 77.1%. 3, 使用分类和global distance 做mutual loss时，另个模型都能收敛，最后resnnet50 rank-1 79.5%,inceptionv4 75.2%.

请教问题，只使用分类做mutual loss 时 inceptionv4先收敛后发散的原因可能是什么？
或者对上述现象是否还有别的建议？

谢谢！

**Comment by michuanhaohao** [comment]
是不是inception的性能不行，mutual learning如果两个网络差距太大的话，网络会被带偏的。黄厚景的涨点结果也是在两个resent50上得到的吧。大概理解为一个大佬和一个猪队友一起组队，大佬也会被带崩。




祝好




罗浩 浙江大学



-----原始邮件-----
发件人:Singularity <notifications@github.com>
发送时间:2019-03-05 22:11:21 (星期二)
收件人: michuanhaohao/AlignedReID <AlignedReID@noreply.github.com>
抄送: "Hao Luo" <haoluocsc@zju.edu.cn>, Comment <comment@noreply.github.com>
主题: Re: [michuanhaohao/AlignedReID] About mutual learning (#18)



你好，我按着https://github.com/huanghoujing/AlignedReID-Re-Production-Pytorch思路做了deep mutual learning .使用resnet50 ,inceptionv4 两个模型，DukeMTMCreID数据集。发现个现象：单独训练时都能收敛，但是mutual learning时 1，只使用分类做mutual loss 时resnet50能收敛但最后效果不如单独训练时（测试rank-1 83%），inceptionv4 刚开始收敛大概15epochs后开始发散，发散到一定程度后稳定， 最后对resetnet50测试 rank-1 82.1% 。2，只使用global distance做mutual loss 时两个模型都能收敛最后测试resnet50 rank-1 80.0%，inceptionv4 rank-1 77.1%. 3, 使用分类和global distance 做mutual loss时，另个模型都能收敛，最后resnnet50 rank-1 79.5%,inceptionv4 75.2%.

请教问题，只使用分类做mutual loss 时 inceptionv4先收敛后发散的原因可能是什么？
或者对上述现象是否还有别的建议？

谢谢！

**Comment by Qidian213** [comment]
谢谢，我再研究一下。
