### ISSUE TITLE
Pretrained Models cannot be read.

### ISSUE THREAD

**Issue by iamkucuk** [michuanhaohao/AlignedReID#19]
I'm trying to test out the pretrained models, however it fails to read those models. I downloaded it from Google Drive. What can I do?

I have another question too. Can I run the code on PyTorch 1.0 ?

**Comment by michuanhaohao** [comment]
@iamkucuk There may some difference between pytorch1.0 and pytorch0.4. I suggest you run the code with pytorch0.4.
