### ISSUE TITLE
正负样本之间距离的统计

### ISSUE THREAD

**Issue by Qidian213** [michuanhaohao/AlignedReID#21]
训练过程中对正负样本之间的距离做了个统计，方便确定正负样本之间阈值。Resnet50 ,DukeMTMC-reID数据集。
![an](https://user-images.githubusercontent.com/15031441/54121432-5ca84d80-4435-11e9-8888-769132e1e1bb.png)
![ap](https://user-images.githubusercontent.com/15031441/54121446-63cf5b80-4435-11e9-9801-05b61a3d56e1.png)

**Comment by michuanhaohao** [comment]
@Qidian213 非常感谢
