### ISSUE TITLE
生成的模型文件不知道怎么使用

### ISSUE THREAD

**Issue by hsqaihkl** [michuanhaohao/AlignedReID#23]
@michuanhaohao 您好，训练生成的模型文件怎么使用呀？生成了best_model.pth.tar   解压也出错，直接调用也不行。是不是我训练的方式没对？还是什么呀？

**Comment by michuanhaohao** [comment]
@hsqaihkl 你看下readme里的介绍，用--resume 指令就可以load 模型了

**Comment by hsqaihkl** [comment]
@michuanhaohao 因为我直接就把它download下来，然后使用pycharm这个ide运行train_alignedreid.py，然后经过长时间的训练，以为训练完了呢，没想到训练完还得再走一步。谢了哈，现在是在运行中了，还没完成后续有问题的话我也直接找您了哦，麻烦您到时候帮忙解决一下了，您看可以吧？先万分感谢了

**Comment by 2110317008** [comment]
> @hsqaihkl 你看下readme里的介绍，用--resume 指令就可以load 模型了

best_model.pth.tar 和checkpoint_ep300.pth.tar的区别是什么？
