### ISSUE TITLE
Anyone runs successfully in Pytorch1.0 and python3?

### ISSUE THREAD

**Issue by wait1988** [michuanhaohao/AlignedReID#24]

**Comment by michuanhaohao** [comment]
Python3 is available. Pytorch 1.0 has not been tested yet.

**Comment by nemesta29** [comment]
Yes,
Used on Python3.6 and Torch 1.2
Need to make one change in serialization.py for torch

Use encoding='latin-1' in the unpickler options (line 571 for torch 1.2)
