### ISSUE TITLE
how to compute the global feat for inference 

### ISSUE THREAD

**Issue by hengshan123** [michuanhaohao/AlignedReID#25]
Hi thank you for your work, i find the local feat in Alignedreid_demo.py. But when used for inference  the global feat is good enough, how to compute the global feat?

**Comment by michuanhaohao** [comment]
Check the README please. 'Test with Global'

**Comment by BabuTango** [comment]
@michuanhaohao Can you please explain what is global feat. Since I'm new to this, I'm confused with too many variables.
