### ISSUE TITLE
System output and custom dataset

### ISSUE THREAD

**Issue by Khreas** [michuanhaohao/AlignedReID#3]
Hello,

I read through the [AlignedReID paper](https://arxiv.org/abs/1711.08184) and decided to give the system a try. I'm new to the person re-identification field and I wanted to check how good it performs on some personal pictures.

When dealing with object detection systems, we usually input a picture and the system returns a class. In the case of person re-identification, I'm a bit lost. So here are my questions:

1. From what I understand, the system's input is a set of N pictures. But what is its output? Does the system calculates distances betwen all the images and yield the couple of images that has the lowest distance? From the following picture, I'd say that the output is the triplet loss, but it doesn't make sense to me ... 

![image](https://user-images.githubusercontent.com/10131735/42099999-470cca94-7bbf-11e8-88ce-91efaef85d79.png)

2.  Let's say that I have 1000 images from my own dataset (not used to train the network). By loading the pre-trained weights of the system, and given 1 picture of my dataset, will I be able to retrieve all the pictures of the similar person using your code?

Thanks in advance!

**Comment by michuanhaohao** [comment]
1. Yes. Calculate distances betwen all the images and yield the couple of images that has the lowest distance.

2. Yes. However, there exists domian bias between different datasets. Maybe the performance will be worse.
