### ISSUE TITLE
different results by a large margin from the paper and your repo

### ISSUE THREAD

**Issue by jpainam** [michuanhaohao/AlignedReID#4]
HI! I came across your paper; but the reported results on market are very differents by a large margin. In this repo, you report `88.2/73.1` for  `rank1/mAP` without re-ranking but in the paper ,we find `91.8/79.3` without re-ranking results. A margin of  `3.6%/6.2%` is too high. Can you explain this?

**Comment by michuanhaohao** [comment]
@jpainam The results of original paper are obtained with merge all datasets. In our new paper AlignedReID++, we train and test our method on each dataset. See README for details and wait our new paper.

**Comment by jpainam** [comment]
@michuanhaohao At the time I opened this issue, your readme didn't mention that the results concern your new paper. You just made an update. A kind reply was expected. I suggest you open a new repo for your new paper. The title of this repo still refers to `Official Reproduce AlignedReID: Surpassing Human-Level Performance in Person Re-Identification using Pytorch.` while the readme is totally different

**Comment by michuanhaohao** [comment]
@jpainam Thanks for your suggestion. New paper just repairs some mistakes of the origin paper, so the code can be used for AlignedReID. Our new paper is under review and cites the link to this project. Therefore, we can not open a new project before it published or rejected. But I changed the title in minutes age.

**Comment by jpainam** [comment]
Thank. My paper https://github.com/jpainam/SLS_ReID also under review. I was expecting your answer before reporting your results.

**Comment by michuanhaohao** [comment]
@jpainam Good luck for you!!! It is really sorry that i was focus on writing the paper and didn't watch the Github days ago.
