### ISSUE TITLE
Hi, can you share the paper Alignedreid＋+,thx

### ISSUE THREAD

**Issue by Gaoyiminggithub** [michuanhaohao/AlignedReID#5]
Hi, can you share the paper : Alignedreid＋+: Dynamically Matching Local Information for Person Re-Identification
i want to know what different between it and Alignedreid. thx!

**Comment by michuanhaohao** [comment]
@Gaoyiminggithub  Thanks for your attention! The paper is under review and will be opened when accepted.

**Comment by Gaoyiminggithub** [comment]
@michuanhaohao NIPS ?

**Comment by michuanhaohao** [comment]
@Gaoyiminggithub Pattern Recognition.

**Comment by Gaoyiminggithub** [comment]
@michuanhaohao Got it, i will wait, thx.
