### ISSUE TITLE
Program code learning and running problems

### ISSUE THREAD

**Issue by jixiedy** [michuanhaohao/AlignedReID#7]
Hello,  I have two questions about your program:
First, as a beginner, I can't understand your program code very well. Can you give me some advice ?
Second, I want to use other dataset for training. What files and parameters should I modify?
Sincerely hope to get your answer, thank you!

**Comment by michuanhaohao** [comment]
The main file is train_alignedreid.py, so reading this file firstly and its called functions may be helpful.

Please modify the data_manager.py and write a new 'class' like 'Class Market1501'.

**Comment by michuanhaohao** [comment]
Solved
