### ISSUE TITLE
Not able to download pre-trained model.

### ISSUE THREAD

**Issue by kai-kaushik** [michuanhaohao/AlignedReID#8]
Hi, I have been trying to download the pre-trained model for a while not. Firstly, I faced the issue when Baidu did not let me download the file in my Ubuntu system. I was asking me to download BaiduNetDisk software. But I could not install it on Ubuntu as only .exe file is available and not supported  by wine in U Ubuntu. I also created an account in Baidu and copied the Files into my net-disk, but I was again unable to download it from there since it again asked me to download the BaiduNetDisk software.

Later I used the Baidu-dl chrome extension and J-Downloader to download your file, but I am unable to unzip it. It is asking me for a password. Please solve this issue. Thanks.

**Comment by michuanhaohao** [comment]
@Kumara-Kaushik OK, I will upload the models to the Google Drive at once. Please wait a day or two.

**Comment by ebinthomas** [comment]
Please upload the models to google drive

**Comment by michuanhaohao** [comment]
@ebinthomas Google Drive: [https://drive.google.com/open?id=1-QApSAY51NvRcQgyUxCn8lP1sSWCeMVg](https://drive.google.com/open?id=1-QApSAY51NvRcQgyUxCn8lP1sSWCeMVg)
