### ISSUE TITLE
No drastic difference btw similar and dissimilar images

### ISSUE THREAD

**Issue by kai-kaushik** [michuanhaohao/AlignedReID#9]
Hi, I downloaded the resnet pretrained model weights and ran the demo. I test it with two different images of people as well as two images of the same person whose images are slightly cropped with respect to each other. 
Ideally the distance btw the same images should be less while the distance btw the different images should be more. But that's not the result I am getting.
In fact, The distance btw the same person is more than the distance btw dissimilar people as seen in the pictures below.

![figure_4](https://user-images.githubusercontent.com/33788839/45644489-7ba7d180-badb-11e8-9601-283fbb1d128b.png)
![figure_2](https://user-images.githubusercontent.com/33788839/45644370-3aafbd00-badb-11e8-8499-25a064d78eea.png)

Why is this happening?

**Comment by michuanhaohao** [comment]
@Kumara-Kaushik 

- The method just corrects misalignment as much as possible. (0.77-068=0.09) > (0.52-0.50 = 0.02), so it pull more distance of the first image pair. 

-  You **should train the model on the ReID dataset** while not using the ImageNet model to do the ReID task. The feature distance of the negative pair is much less than the positive pair.

**Comment by BabuTango** [comment]
@michuanhaohao can't understand. can you please elaborate.

I too face the same issue. 
1. Two different persons with same angle and height are getting matched(aligned distance is less)
2. Two same persons with different angle and crops are not getting matched(aligneddistance is more)  

We should consider the aligned distance only right?? or should we use original distance
